/* eslint-disable @next/next/no-img-element */
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/1e3mWOIs0yJ
 */
import { CardHeader, CardContent, Card } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { useEffect, useRef, useState } from "react";

interface DropZoneProps {
  id: string;
  onChange: (files: File[]) => void;
  disabled?: boolean;
}

export function DropZone({ id, onChange, disabled }: DropZoneProps) {
  return (
    <div className="w-full max-w-md mx-auto flex items-center gap-3">
      <div className="grid w-full max-w-sm items-center gap-1.5">
        <Input
          multiple
          className="py-2"
          id={id}
          type="file"
          onChange={(event) => {
            const files = Array.from(event.target.files ?? []);
            onChange(files);
          }}
        />
      </div>
      <Button size="sm" variant="outline">
        Upload Image
      </Button>
    </div>
  );
}
