/* eslint-disable @next/next/no-img-element */
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/1e3mWOIs0yJ
 */
import { CardHeader, CardContent, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { useEffect, useRef, useState } from "react"

interface DropZoneProps {
  id: string
  onChange: (files: File[]) => void
  disabled?: boolean
}

export function DropZone(
  { id, onChange, disabled }: DropZoneProps
) {

  return (
    <div className="w-full max-w-md mx-auto">
      <Card className="flex flex-col items-center py-10 px-5 space-y-8 bg-gray-50 rounded-lg shadow">
        <CardHeader className="text-2xl font-bold text-center">Image Upload</CardHeader>
        <CardContent className="flex flex-col items-center space-y-4">
          <div className="grid w-full max-w-sm items-center gap-1.5">
            <Label htmlFor={id}>Select an image to upload</Label>
            <Input
              multiple
              className="py-2"
              id={id}
              type="file"
              onChange={(event) => {
                const files = Array.from(event.target.files ?? []);
                onChange(files);
              }}
            />
            <p className="text-sm text-gray-500 dark:text-gray-400">The selected image will be displayed above.</p>
          </div>
          <Button size="lg">Upload Image</Button>
        </CardContent>
      </Card>
    </div>
  )
}
